apiVersion: v1
kind: Service
metadata:
  name: dns-service-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "web.default.cluster.local"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
    - name: dnsudp
      protocol: UDP
      port: 80
      targetPort: 8000
  selector:
    app: dns
