apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webmon-sm
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: webmon
  endpoints:
  - port: exporter
