version: '3.4'
services: 
  elasticsearch_exporter:
    image: docker-registry.ecg.so/dk/docker-hub/justwatch/elasticsearch_exporter:1.0.2
    command:
      - '-es.uri=http://elasticsearch-master:9200'
      - '-es.all'
      - '-es.indices'
    ports:
      - "9108:9108"
